env: safetyGraphics
label: QT Explorer - Module
name: qTexplorerNew
type: module
package: qtexplorer
export: true
domain: 
  - ecg
  - dm
workflow:
  ui: QT_Explorer_ui
  server: QT_Explorer_server
links:
  safetyCharts: https://github.com/SafetyGraphics/safetycharts
