env: safetyGraphics
label: QT Outlier Explorer - Module
name: qTexplorer
type: module
package: qtexplorer
export: true
order: 1
domain: 
  - ecg
workflow:
  ui: QT_OutlierExplorer_ui
  server: QT_OutlierExplorer_server
links:
  qtexplorer: https://github.com/SafetyGraphics/qtexplorer
