env: safetyGraphics
label: QT Paneled Outlier Explorer
type: htmlwidget
domain: 
  - ecg
package: qtexplorer
export: true
order: 3
workflow:
  init: init_paneledOutlierExplorer
  widget: paneledOutlierExplorer
links:
  Homepage: https://github.com/RhoInc/paneled-outlier-explorer
  Wiki: https://github.com/RhoInc/paneled-outlier-explorer/wiki 
  Issues: https://github.com/RhoInc/paneled-outlier-explorer/issues
  Demo: https://rhoinc.github.io/paneled-outlier-explorer/test-page/

