env: safetyGraphics
label: QT Results Over Time
type: htmlwidget
package: qtexplorer
export: true
order: 3
domain: 
  - ecg
workflow:
  init: init_safetyResultsOverTime
  widget: safetyResultsOverTime
links:
  Homepage: https://github.com/RhoInc/safety-results-over-time
  Wiki: https://github.com/RhoInc/safety-results-over-time/wiki
  Issues: https://github.com/RhoInc/safety-results-over-time/issues
  Demo: https://rhoinc.github.io/safety-results-over-time/test-page/
  qtexplorer: https://github.com/SafetyGraphics/qtexplorer
