env: safetyGraphics
label: QT Outlier Explorer
type: htmlwidget
package: qtexplorer
export: true
order: 2
domain: 
  - ecg
workflow:
  init: init_safetyOutlierExplorer
  widget: safetyOutlierExplorer
links:
  Homepage: https://github.com/RhoInc/safety-outlier-explorer
  Wiki: https://github.com/RhoInc/safety-outlier-explorer/wiki 
  Issues: https://github.com/RhoInc/safety-outlier-explorer/issues
  Demo: https://rhoinc.github.io/safety-outlier-explorer/test-page/
  qtexplorer: https://github.com/SafetyGraphics/qtexplorer
