env: safetyGraphics
label: QT Histogram
type: htmlwidget
package: qtexplorer
domain: 
  - ecg
export: true
order: 4
workflow:
  widget: safetyHistogram
links:
  Homepage: https://github.com/RhoInc/safety-histogram
  Wiki: https://github.com/RhoInc/safety-histogram/wiki 
  Issues: https://github.com/RhoInc/safety-histogram/issues
  Demo: https://rhoinc.github.io/safety-histogram/test-page/
  qtexplorer: https://github.com/SafetyGraphics/qtexplorer

