env: safetyGraphics
label: QT Scatterplots
name: qtexplorer
type: module
package: qtexplorer
export: true
order: 2
domain: 
  - ecg
  - dm
workflow:
  ui: QT_Explorer_ui
  server: QT_Explorer_server
links:
  Homepage: https://github.com/safetygraphics/qtexplorer
